services:
  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-test}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./infrastructure/observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - prometheus
      - tempo
      - loki
    profiles:
      - lgtm

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-otlp-receiver
    volumes:
      - ./infrastructure/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    profiles:
      - lgtm

  # Loki for logs
  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infrastructure/observability/loki/local-config.yaml:/etc/loki/local-config.yaml
    user: "0" # Run as root to avoid permission issues
    ports:
      - "3100:3100"
    profiles:
      - lgtm

  # Tempo for traces
  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo-config.yaml" ]
    volumes:
      - ./infrastructure/observability/tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml
    ports:
      - "3200:3200" # tempo
      - "14317:4317" # otlp grpc
    user: "0" # Run as root to avoid permission issues

  # Grafana for visualization
  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    volumes:
      - ./infrastructure/observability/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./infrastructure/observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./infrastructure/observability/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    profiles:
      - lgtm

volumes:
  db_data:
