quarkus:

  management:
    enabled: true

  micrometer:
    enabled: true
    export:
      prometheus:
        enabled: true
    binder:
      http-server:
        enabled: true
      jvm:
        enabled: true

  grpc:
    server:
      port: 9002

  log:
    metrics:
      enabled: true

  otel:
    enabled: true
    metrics:
      enabled: true
    metric:
      export:
        interval: 5s
    logs:
      enabled: true
    instrument:
      jvm-metrics: false
      http-server-metrics: false

  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}

    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?search_path=public
      detect-statement-leaks: true
      pooling-enabled: true

  http:
    cors:
      enabled: false
    enable-compression: true
    access-log:
      enabled: true
    header:
      "X-Content-Type-Options":
        value: nosniff

  jackson:
    fail-on-unknown-properties: true

  hibernate-orm:
    database:
      default-schema: public

