global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]  # OTLP metrics endpoint

#  - job_name: 'java-services'
#    metrics_path: /q/metrics
#    static_configs:
#      - targets: [ 'host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082' ] # Java services